version: '3.8'
services:
  backend-data:
    container_name: django_data
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8000
    volumes:
      - .:/usr/src/app
    # depends_on:
    #   - db

  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python -u consumer.py'
  #   depends_on:
  #     - db
  
  # db:
  #   image: postgres
  #   container_name: pgdb_users
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - /postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432


    